---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-wordpress
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: darwimroy1900/wordpress:~v0.1
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shuhai-01
  source:
    repoURL: https://github.com/shuai190060/vault.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true