
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-flask

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: app-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      # annotations:
      #  instrumentation.opentelemetry.io/inject-python: "true"
      #  instrumentation.opentelemetry.io/container-names: "flask-app"
    spec:
      containers:
        - name: flask-app
          image: darwimroy1900/flask_sample:latest
          ports:
            - containerPort: 5000



---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: app-flask
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # type: LoadBalancer
  type: ClusterIP
