# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: cert-manager
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://charts.jetstack.io/jetstack
#     targetRevision: v1.10.1
#     chart: cert-manager
#     helm:
#       version: v3
#       releaseName: cert-manager
#       passCredentials: false
#       # parameters:
#       #   - name: ""
#       #     value: v0.6.2
#       values: |
#         installCRDs: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: cert-manager
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
#     syncOptions:
#       - Validate=true
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true