---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com/
    targetRevision: 0.24.1 
    chart: vault
    helm:
      version: v3
      releaseName: vault
      passCredentials: false
      parameters:
      - name: "server.ha.enabled"
        value: "true"
      - name: "server.ha.raft.enabled"
        value: "true"
      # # for quick test in the dev mode
      # - name: "server.dev.enabled"
      #   value: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true