---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql
  namespace: app
  labels:
    prometheus: watched
spec:
  endpoints:
  - port: http
    interval: 60s
    scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
    - app
  selector:
    matchLabels:
      app: mysql-exporter