#----------------------------------------------------------------------------------------------------
# storage
#----------------------------------------------------------------------------------------------------

# # volume for the worldpress
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: worldpress-local-pv
# spec:
#   capacity:
#     storage: 100M
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: "/var/www/html"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - cka-test-control-plane

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worldpress-local-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: local-storage
  # storageClassName: efs

#----------------------------------------------------------------------------------------------------
# wordpress app
#----------------------------------------------------------------------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest 
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service.default.svc.cluster.local"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_CHARSET
          value: "utf8mb4"
        - name: WORDPRESS_DB_COLLATE
          value: "utf8mb4_unicode_ci"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: worldpress-local-pvc


#----------------------------------------------------------------------------------------------------
# service
#----------------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: ClusterIP
  # type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 30080
