

#----------------------------------------------------------------------------------------------------
# wordpress storage pvc
#----------------------------------------------------------------------------------------------------
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worldpress-local-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  storageClassName: ebs-sc 


#----------------------------------------------------------------------------------------------------
# wordpress app
#----------------------------------------------------------------------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: app
  labels:
    app: wordpress
    version: "01"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: darwimroy1900/wordpress:$$VERSION
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql-service.default.svc.cluster.local"
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_NAME
          value: "wordpress"
        - name: WORDPRESS_DB_CHARSET
          value: "utf8mb4"
        - name: WORDPRESS_DB_COLLATE
          value: "utf8mb4_unicode_ci"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: worldpress-local-pvc


#----------------------------------------------------------------------------------------------------
# service
#----------------------------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: app
spec:
  selector:
    app: wordpress
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80

