apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: app
spec:
  encryptedData:
    mysql-password: AgBbR1lCh/lEgjVgyDd++TUSzDxAy6eQMA7CwOE1hYmpiPrKA+0xfeEzopjf63vT9KEyaqGm7LFuJuhVsZ6beL1rokm0uRFyhIUiRAgOwe3kvGVIlS6zxZrOnFPhoQ9HtorhCvwmb1oEF+gYtIQxKqu53+NaBaGFfmwGrqs8WCKWcaLcLJ4XijRF/Y8zcS1GREPmiTGyhQDqJGfnRbMLoAKl0dWkjhnT3/OAGn9le6A1IeOZSd0TdOoBaxMidxvamoQMMydO6lAdm72MR63W5E2kJTiBjCHtINW6cvEML71k6BLjjPQLXIzYMiGvi19BLzGYxO6NVF7ONqLEvO48K2bO47VPbm2gG1G3O8XnV36dx/du0ccmgXIp/4T/94Ef0DsNlYcOrJTJ7m2k3cKiQrzeHMdWK/iHH1eqtvAmqHLMnGDNqWTvjpv4tK0T+JG2Ohgq45PcYGz8mB3zTY1Fvh1m1N8UUZTyKTAeQNR4fFL5zKZ6ct9/cNoOUOIEMCmOa8GkeIQilX3Z21bRZ2WDPYom/3Seb83Dj0ZbuQ4KPaj+HzjwFmNZ+HuWxNaDnFoy/MXlZi912KFoL7pu+1///HftvUy4u062nk8v2yWUym6tIHF0WP+845XYxPm8DQoSmzENfPEOTGt+/j9oKL35/lGhhP7SEToQJW6aRbG5aJa56gRtUpcLX4Tl2bv8bfgE5YUqBag=
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: app
    type: Opaque

