---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-wordpress
  namespace: app
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: shuai190060@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-wordpress
    solvers:
    - http01:
        ingress:
          class:  external-nginx