# ingress to expose the wordpress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
  namespace: app
  annotations:
      cert-manager.io/issuer: letsencrypt-wordpress
spec:
  ingressClassName: external-nginx
  tls: 
  - hosts:
    - wordpress.shuhai.de
    secretName: wordpress-shuhai-de-key-pair
  rules:
  - host: wordpress.shuhai.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-service
            port:
              number: 80