
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-mysql-secret
  template:
    metadata:
      labels:
        app: busybox-mysql-secret
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-mysql: "secret/db/mysql"
        vault.hashicorp.com/agent-inject-template-mysql: |
          {{- with secret "secret/db/mysql" -}}
          {
            "password": "{{ .Data.password }}"
          }
          {{- end }}
        vault.hashicorp.com/role: "mysql-secret-role"
    spec:
      serviceAccountName: mysql-secret
      containers:
        - name: busybox
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - |
              sleep 3600
