---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt-app-nginx
  namespace: app
spec:
  secretName: acme-crt-secret-app-nginx
  dnsNames:
  - app.shuhai.de
  issuerRef:
    name: app-nginx-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    group: cert-manager.io